version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=wongames
      - POSTGRES_USER=wongames
      - POSTGRES_PASSWORD=wongames123
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
